\set ON_ERROR_STOP on

BEGIN;

DO $$
BEGIN
    IF current_user <> 'queryguard_owner' THEN
        RAISE EXCEPTION
            'ERP schema must be applied as queryguard_owner, not %', current_user;
    END IF;
END
$$;

CREATE TABLE erp.product_categories (
    category_id bigint GENERATED BY DEFAULT AS IDENTITY,
    category_name varchar(100) NOT NULL,
    parent_category_id bigint,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    display_order smallint NOT NULL DEFAULT 0,
    CONSTRAINT pk_product_categories PRIMARY KEY (category_id),
    CONSTRAINT uq_product_categories_name UNIQUE (category_name),
    CONSTRAINT fk_product_categories_parent
        FOREIGN KEY (parent_category_id)
        REFERENCES erp.product_categories (category_id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_product_categories_name_nonempty
        CHECK (btrim(category_name) <> ''),
    CONSTRAINT ck_product_categories_no_self_parent
        CHECK (parent_category_id IS NULL OR parent_category_id <> category_id),
    CONSTRAINT ck_product_categories_display_order
        CHECK (display_order >= 0)
);

CREATE TABLE erp.suppliers (
    supplier_id bigint GENERATED BY DEFAULT AS IDENTITY,
    supplier_code varchar(20) NOT NULL,
    supplier_name varchar(150) NOT NULL,
    contact_name varchar(150),
    email varchar(254),
    phone varchar(30),
    country_code character(2) NOT NULL,
    state_province varchar(100),
    city varchar(100),
    payment_terms_days smallint NOT NULL DEFAULT 30,
    rating numeric(3, 2),
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_suppliers PRIMARY KEY (supplier_id),
    CONSTRAINT uq_suppliers_code UNIQUE (supplier_code),
    CONSTRAINT ck_suppliers_code_nonempty CHECK (btrim(supplier_code) <> ''),
    CONSTRAINT ck_suppliers_name_nonempty CHECK (btrim(supplier_name) <> ''),
    CONSTRAINT ck_suppliers_country_code
        CHECK (country_code ~ '^[A-Z]{2}$'),
    CONSTRAINT ck_suppliers_payment_terms
        CHECK (payment_terms_days BETWEEN 0 AND 365),
    CONSTRAINT ck_suppliers_rating
        CHECK (rating IS NULL OR rating BETWEEN 0 AND 5)
);

CREATE TABLE erp.customers (
    customer_id bigint GENERATED BY DEFAULT AS IDENTITY,
    customer_code varchar(20) NOT NULL,
    customer_name varchar(150) NOT NULL,
    customer_segment varchar(20) NOT NULL,
    email varchar(254),
    phone varchar(30),
    country_code character(2) NOT NULL,
    state_province varchar(100),
    city varchar(100),
    registered_on date NOT NULL,
    credit_limit numeric(14, 2) NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_customers PRIMARY KEY (customer_id),
    CONSTRAINT uq_customers_code UNIQUE (customer_code),
    CONSTRAINT uq_customers_email UNIQUE (email),
    CONSTRAINT ck_customers_code_nonempty CHECK (btrim(customer_code) <> ''),
    CONSTRAINT ck_customers_name_nonempty CHECK (btrim(customer_name) <> ''),
    CONSTRAINT ck_customers_segment
        CHECK (customer_segment IN ('SMB', 'MID_MARKET', 'ENTERPRISE')),
    CONSTRAINT ck_customers_country_code
        CHECK (country_code ~ '^[A-Z]{2}$'),
    CONSTRAINT ck_customers_credit_limit CHECK (credit_limit >= 0)
);

CREATE TABLE erp.warehouses (
    warehouse_id bigint GENERATED BY DEFAULT AS IDENTITY,
    warehouse_code varchar(20) NOT NULL,
    warehouse_name varchar(120) NOT NULL,
    country_code character(2) NOT NULL,
    state_province varchar(100),
    city varchar(100) NOT NULL,
    capacity_units numeric(14, 2) NOT NULL,
    opened_on date NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_warehouses PRIMARY KEY (warehouse_id),
    CONSTRAINT uq_warehouses_code UNIQUE (warehouse_code),
    CONSTRAINT ck_warehouses_code_nonempty CHECK (btrim(warehouse_code) <> ''),
    CONSTRAINT ck_warehouses_name_nonempty CHECK (btrim(warehouse_name) <> ''),
    CONSTRAINT ck_warehouses_country_code
        CHECK (country_code ~ '^[A-Z]{2}$'),
    CONSTRAINT ck_warehouses_city_nonempty CHECK (btrim(city) <> ''),
    CONSTRAINT ck_warehouses_capacity CHECK (capacity_units > 0)
);

CREATE TABLE erp.products (
    product_id bigint GENERATED BY DEFAULT AS IDENTITY,
    sku varchar(30) NOT NULL,
    product_name varchar(150) NOT NULL,
    category_id bigint NOT NULL,
    supplier_id bigint NOT NULL,
    unit_of_measure varchar(10) NOT NULL,
    unit_cost numeric(14, 2) NOT NULL,
    list_price numeric(14, 2) NOT NULL,
    launched_on date NOT NULL,
    discontinued_on date,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_products PRIMARY KEY (product_id),
    CONSTRAINT uq_products_sku UNIQUE (sku),
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id)
        REFERENCES erp.product_categories (category_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_products_supplier
        FOREIGN KEY (supplier_id)
        REFERENCES erp.suppliers (supplier_id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_products_sku_nonempty CHECK (btrim(sku) <> ''),
    CONSTRAINT ck_products_name_nonempty CHECK (btrim(product_name) <> ''),
    CONSTRAINT ck_products_unit_of_measure
        CHECK (unit_of_measure IN ('EACH', 'BOX', 'KG', 'LITER')),
    CONSTRAINT ck_products_unit_cost CHECK (unit_cost >= 0),
    CONSTRAINT ck_products_list_price CHECK (list_price >= 0),
    CONSTRAINT ck_products_dates
        CHECK (discontinued_on IS NULL OR discontinued_on >= launched_on)
);

CREATE TABLE erp.inventory (
    product_id bigint NOT NULL,
    warehouse_id bigint NOT NULL,
    quantity_on_hand numeric(14, 2) NOT NULL DEFAULT 0,
    quantity_reserved numeric(14, 2) NOT NULL DEFAULT 0,
    reorder_level numeric(14, 2) NOT NULL DEFAULT 0,
    last_stocktake_date date,
    CONSTRAINT pk_inventory PRIMARY KEY (product_id, warehouse_id),
    CONSTRAINT fk_inventory_product
        FOREIGN KEY (product_id)
        REFERENCES erp.products (product_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_inventory_warehouse
        FOREIGN KEY (warehouse_id)
        REFERENCES erp.warehouses (warehouse_id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_inventory_nonnegative_quantities
        CHECK (
            quantity_on_hand >= 0
            AND quantity_reserved >= 0
            AND reorder_level >= 0
        ),
    CONSTRAINT ck_inventory_reserved_not_above_stock
        CHECK (quantity_reserved <= quantity_on_hand)
);

CREATE TABLE erp.employees (
    employee_id bigint GENERATED BY DEFAULT AS IDENTITY,
    employee_number varchar(20) NOT NULL,
    first_name varchar(80) NOT NULL,
    last_name varchar(80) NOT NULL,
    email varchar(254) NOT NULL,
    job_title varchar(120) NOT NULL,
    department varchar(20) NOT NULL,
    manager_id bigint,
    warehouse_id bigint,
    hire_date date NOT NULL,
    termination_date date,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_employees PRIMARY KEY (employee_id),
    CONSTRAINT uq_employees_number UNIQUE (employee_number),
    CONSTRAINT uq_employees_email UNIQUE (email),
    CONSTRAINT fk_employees_manager
        FOREIGN KEY (manager_id)
        REFERENCES erp.employees (employee_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_employees_warehouse
        FOREIGN KEY (warehouse_id)
        REFERENCES erp.warehouses (warehouse_id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_employees_number_nonempty CHECK (btrim(employee_number) <> ''),
    CONSTRAINT ck_employees_first_name_nonempty CHECK (btrim(first_name) <> ''),
    CONSTRAINT ck_employees_last_name_nonempty CHECK (btrim(last_name) <> ''),
    CONSTRAINT ck_employees_job_title_nonempty CHECK (btrim(job_title) <> ''),
    CONSTRAINT ck_employees_department
        CHECK (
            department IN (
                'SALES',
                'PROCUREMENT',
                'WAREHOUSE',
                'FINANCE',
                'OPERATIONS'
            )
        ),
    CONSTRAINT ck_employees_dates
        CHECK (termination_date IS NULL OR termination_date >= hire_date),
    CONSTRAINT ck_employees_no_self_manager
        CHECK (manager_id IS NULL OR manager_id <> employee_id)
);

CREATE TABLE erp.sales_orders (
    sales_order_id bigint GENERATED BY DEFAULT AS IDENTITY,
    order_number varchar(30) NOT NULL,
    customer_id bigint NOT NULL,
    sales_rep_id bigint NOT NULL,
    order_date date NOT NULL,
    required_date date NOT NULL,
    shipped_date date,
    status varchar(20) NOT NULL,
    currency_code character(3) NOT NULL DEFAULT 'USD',
    shipping_amount numeric(14, 2) NOT NULL DEFAULT 0,
    tax_amount numeric(14, 2) NOT NULL DEFAULT 0,
    notes text,
    CONSTRAINT pk_sales_orders PRIMARY KEY (sales_order_id),
    CONSTRAINT uq_sales_orders_number UNIQUE (order_number),
    CONSTRAINT fk_sales_orders_customer
        FOREIGN KEY (customer_id)
        REFERENCES erp.customers (customer_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_sales_orders_sales_rep
        FOREIGN KEY (sales_rep_id)
        REFERENCES erp.employees (employee_id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_sales_orders_number_nonempty CHECK (btrim(order_number) <> ''),
    CONSTRAINT ck_sales_orders_status
        CHECK (status IN ('DRAFT', 'CONFIRMED', 'SHIPPED', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_sales_orders_currency CHECK (currency_code = 'USD'),
    CONSTRAINT ck_sales_orders_shipping_amount CHECK (shipping_amount >= 0),
    CONSTRAINT ck_sales_orders_tax_amount CHECK (tax_amount >= 0),
    CONSTRAINT ck_sales_orders_required_date CHECK (required_date >= order_date),
    CONSTRAINT ck_sales_orders_shipped_date
        CHECK (shipped_date IS NULL OR shipped_date >= order_date)
);

CREATE TABLE erp.sales_order_items (
    sales_order_item_id bigint GENERATED BY DEFAULT AS IDENTITY,
    sales_order_id bigint NOT NULL,
    line_number smallint NOT NULL,
    product_id bigint NOT NULL,
    warehouse_id bigint NOT NULL,
    quantity numeric(12, 2) NOT NULL,
    unit_price numeric(14, 2) NOT NULL,
    discount_percent numeric(5, 2) NOT NULL DEFAULT 0,
    line_total numeric(18, 2)
        GENERATED ALWAYS AS (
            round(quantity * unit_price * (1 - discount_percent / 100), 2)
        ) STORED,
    CONSTRAINT pk_sales_order_items PRIMARY KEY (sales_order_item_id),
    CONSTRAINT uq_sales_order_items_order_line UNIQUE (sales_order_id, line_number),
    CONSTRAINT fk_sales_order_items_order
        FOREIGN KEY (sales_order_id)
        REFERENCES erp.sales_orders (sales_order_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_sales_order_items_product
        FOREIGN KEY (product_id)
        REFERENCES erp.products (product_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_sales_order_items_warehouse
        FOREIGN KEY (warehouse_id)
        REFERENCES erp.warehouses (warehouse_id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_sales_order_items_line_number CHECK (line_number > 0),
    CONSTRAINT ck_sales_order_items_quantity CHECK (quantity > 0),
    CONSTRAINT ck_sales_order_items_unit_price CHECK (unit_price >= 0),
    CONSTRAINT ck_sales_order_items_discount
        CHECK (discount_percent BETWEEN 0 AND 100)
);

CREATE TABLE erp.purchase_orders (
    purchase_order_id bigint GENERATED BY DEFAULT AS IDENTITY,
    purchase_order_number varchar(30) NOT NULL,
    supplier_id bigint NOT NULL,
    warehouse_id bigint NOT NULL,
    buyer_employee_id bigint NOT NULL,
    order_date date NOT NULL,
    expected_date date NOT NULL,
    received_date date,
    status varchar(25) NOT NULL,
    currency_code character(3) NOT NULL DEFAULT 'USD',
    shipping_amount numeric(14, 2) NOT NULL DEFAULT 0,
    notes text,
    CONSTRAINT pk_purchase_orders PRIMARY KEY (purchase_order_id),
    CONSTRAINT uq_purchase_orders_number UNIQUE (purchase_order_number),
    CONSTRAINT fk_purchase_orders_supplier
        FOREIGN KEY (supplier_id)
        REFERENCES erp.suppliers (supplier_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_purchase_orders_warehouse
        FOREIGN KEY (warehouse_id)
        REFERENCES erp.warehouses (warehouse_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_purchase_orders_buyer
        FOREIGN KEY (buyer_employee_id)
        REFERENCES erp.employees (employee_id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_purchase_orders_number_nonempty
        CHECK (btrim(purchase_order_number) <> ''),
    CONSTRAINT ck_purchase_orders_status
        CHECK (
            status IN (
                'DRAFT',
                'ORDERED',
                'PARTIALLY_RECEIVED',
                'RECEIVED',
                'CANCELLED'
            )
        ),
    CONSTRAINT ck_purchase_orders_currency CHECK (currency_code = 'USD'),
    CONSTRAINT ck_purchase_orders_shipping_amount CHECK (shipping_amount >= 0),
    CONSTRAINT ck_purchase_orders_expected_date CHECK (expected_date >= order_date),
    CONSTRAINT ck_purchase_orders_received_date
        CHECK (received_date IS NULL OR received_date >= order_date)
);

CREATE TABLE erp.purchase_order_items (
    purchase_order_item_id bigint GENERATED BY DEFAULT AS IDENTITY,
    purchase_order_id bigint NOT NULL,
    line_number smallint NOT NULL,
    product_id bigint NOT NULL,
    ordered_quantity numeric(12, 2) NOT NULL,
    received_quantity numeric(12, 2) NOT NULL DEFAULT 0,
    unit_cost numeric(14, 2) NOT NULL,
    line_total numeric(18, 2)
        GENERATED ALWAYS AS (round(ordered_quantity * unit_cost, 2)) STORED,
    CONSTRAINT pk_purchase_order_items PRIMARY KEY (purchase_order_item_id),
    CONSTRAINT uq_purchase_order_items_order_line
        UNIQUE (purchase_order_id, line_number),
    CONSTRAINT fk_purchase_order_items_order
        FOREIGN KEY (purchase_order_id)
        REFERENCES erp.purchase_orders (purchase_order_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_purchase_order_items_product
        FOREIGN KEY (product_id)
        REFERENCES erp.products (product_id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_purchase_order_items_line_number CHECK (line_number > 0),
    CONSTRAINT ck_purchase_order_items_ordered_quantity CHECK (ordered_quantity > 0),
    CONSTRAINT ck_purchase_order_items_received_quantity
        CHECK (received_quantity BETWEEN 0 AND ordered_quantity),
    CONSTRAINT ck_purchase_order_items_unit_cost CHECK (unit_cost >= 0)
);

CREATE TABLE erp.product_returns (
    return_id bigint GENERATED BY DEFAULT AS IDENTITY,
    return_number varchar(30) NOT NULL,
    sales_order_item_id bigint NOT NULL,
    return_date date NOT NULL,
    quantity numeric(12, 2) NOT NULL,
    reason varchar(30) NOT NULL,
    status varchar(20) NOT NULL,
    refund_amount numeric(14, 2) NOT NULL DEFAULT 0,
    processed_by_employee_id bigint,
    notes text,
    CONSTRAINT pk_product_returns PRIMARY KEY (return_id),
    CONSTRAINT uq_product_returns_number UNIQUE (return_number),
    CONSTRAINT fk_product_returns_order_item
        FOREIGN KEY (sales_order_item_id)
        REFERENCES erp.sales_order_items (sales_order_item_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_product_returns_employee
        FOREIGN KEY (processed_by_employee_id)
        REFERENCES erp.employees (employee_id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_product_returns_number_nonempty CHECK (btrim(return_number) <> ''),
    CONSTRAINT ck_product_returns_quantity CHECK (quantity > 0),
    CONSTRAINT ck_product_returns_reason
        CHECK (
            reason IN (
                'DAMAGED',
                'DEFECTIVE',
                'WRONG_ITEM',
                'CUSTOMER_CHANGED_MIND',
                'OTHER'
            )
        ),
    CONSTRAINT ck_product_returns_status
        CHECK (status IN ('REQUESTED', 'APPROVED', 'RECEIVED', 'REJECTED', 'REFUNDED')),
    CONSTRAINT ck_product_returns_refund_amount CHECK (refund_amount >= 0)
);

-- PostgreSQL creates indexes for primary keys and unique constraints. These
-- additional indexes cover foreign-key lookups and common reporting filters.
CREATE INDEX idx_product_categories_parent
    ON erp.product_categories (parent_category_id);
CREATE INDEX idx_products_category
    ON erp.products (category_id);
CREATE INDEX idx_products_supplier
    ON erp.products (supplier_id);
CREATE INDEX idx_inventory_warehouse
    ON erp.inventory (warehouse_id);
CREATE INDEX idx_employees_manager
    ON erp.employees (manager_id);
CREATE INDEX idx_employees_warehouse
    ON erp.employees (warehouse_id);
CREATE INDEX idx_sales_orders_customer_date
    ON erp.sales_orders (customer_id, order_date DESC);
CREATE INDEX idx_sales_orders_sales_rep_date
    ON erp.sales_orders (sales_rep_id, order_date DESC);
CREATE INDEX idx_sales_orders_status_date
    ON erp.sales_orders (status, order_date DESC);
CREATE INDEX idx_sales_order_items_product
    ON erp.sales_order_items (product_id);
CREATE INDEX idx_sales_order_items_warehouse
    ON erp.sales_order_items (warehouse_id);
CREATE INDEX idx_purchase_orders_supplier_date
    ON erp.purchase_orders (supplier_id, order_date DESC);
CREATE INDEX idx_purchase_orders_warehouse_date
    ON erp.purchase_orders (warehouse_id, order_date DESC);
CREATE INDEX idx_purchase_orders_buyer_date
    ON erp.purchase_orders (buyer_employee_id, order_date DESC);
CREATE INDEX idx_purchase_orders_status_expected_date
    ON erp.purchase_orders (status, expected_date);
CREATE INDEX idx_purchase_order_items_product
    ON erp.purchase_order_items (product_id);
CREATE INDEX idx_product_returns_order_item
    ON erp.product_returns (sales_order_item_id);
CREATE INDEX idx_product_returns_employee
    ON erp.product_returns (processed_by_employee_id);
CREATE INDEX idx_product_returns_date_status
    ON erp.product_returns (return_date, status);

COMMENT ON TABLE erp.product_categories IS
    'Product classification hierarchy used for category-level reporting.';
COMMENT ON TABLE erp.suppliers IS
    'Organizations that supply products to the enterprise.';
COMMENT ON TABLE erp.customers IS
    'Business customers grouped into SMB, mid-market, and enterprise segments.';
COMMENT ON TABLE erp.warehouses IS
    'Physical locations that hold saleable inventory.';
COMMENT ON TABLE erp.products IS
    'Saleable products with a primary supplier, category, cost, and USD list price.';
COMMENT ON TABLE erp.inventory IS
    'Current product quantities by warehouse at the dataset snapshot date.';
COMMENT ON TABLE erp.employees IS
    'Employees involved in sales, procurement, warehousing, finance, and operations.';
COMMENT ON TABLE erp.sales_orders IS
    'Customer sales-order headers; all monetary values use USD.';
COMMENT ON TABLE erp.sales_order_items IS
    'Sales-order lines fulfilled from a warehouse.';
COMMENT ON TABLE erp.purchase_orders IS
    'Supplier purchase-order headers for warehouse replenishment in USD.';
COMMENT ON TABLE erp.purchase_order_items IS
    'Purchase-order lines with ordered and received quantities.';
COMMENT ON TABLE erp.product_returns IS
    'Customer returns linked to the original sales-order line.';

COMMENT ON COLUMN erp.sales_order_items.line_total IS
    'Quantity times unit price after the line discount; excludes tax, shipping, and returns.';
COMMENT ON COLUMN erp.purchase_order_items.line_total IS
    'Ordered quantity times unit cost; excludes order-level shipping.';
COMMENT ON COLUMN erp.product_returns.refund_amount IS
    'Approved or paid refund amount in USD; zero before a refund is assigned.';
COMMENT ON COLUMN erp.inventory.quantity_reserved IS
    'On-hand quantity reserved for open customer orders.';

REVOKE ALL ON ALL TABLES IN SCHEMA erp FROM PUBLIC, queryguard_audit;
GRANT SELECT ON ALL TABLES IN SCHEMA erp TO queryguard_runtime;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA erp
    FROM PUBLIC, queryguard_runtime, queryguard_audit;

COMMIT;
